# Generated by Django 5.0.3 on 2025-05-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookname',
            field=models.CharField(default='未命名書籍', max_length=200),
        ),
    ]
